#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  navigation: uknet_navigation

#Server configuration
enabled: false
server_name: server_name

#Chat Socket
socket:
  IP:
  port: