# Config version, do not update this manually as it could break the config.
version: 1.6.0

#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

# Promotion track for roles.
roles:
  default:
    name: 'Guest'
    prefix: '[Guest]'
    colour: '&#fffdf9'
    weight: 1
  applicant:
    name: 'Applicant'
    prefix: '[Applicant]'
    colour: '&#ffe599'
    weight: 2
  apprentice:
    name: 'Apprentice'
    prefix: '[Apprentice]'
    colour: '&#efb70c'
    weight: 3
  jrbuilder:
    name: 'Jr.Builder'
    prefix: '[Jr.Builder]'
    colour: '&#d78426'
    weight: 4
  builder:
    name: 'Builder'
    prefix: '[Builder]'
    colour: '&#f26868'
    weight: 5
  architect:
    name: 'Architect'
    prefix: '[Architect]'
    colour: '&#ec2a2a'
    weight: 6
  reviewer:
    name: 'Reviewer'
    prefix: '[Reviewer]'
    colour: '&#8be565'
    weight: 7

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Server configuration
#Server types: PLOT, EARTH, LOBBY, TUTORIAL
enabled: false
server_name: server_name
server_type: EARTH

#Lobby info, only necessary if server type is LOBBY.
spawn:
  world: Lobby
  x: 1000.5
  y: 69.0
  z: -129.5
  yaw: -90
  pitch: 0

# Map info. Must be set to enabled to be available.
map:
  enabled: false
  server: lobby
  location:
    world: Lobby
    x: 100.5
    y: 69.0
    z: 100.5
    yaw: 90
    pitch: 0

#Staff features
staff:
  staff_chat:
    enabled: true
  moderation:
    enabled: true

#Tutorials
#Enable if your network contains a server with TeachingTutorials setup.
tutorials:
  enabled: false
  compulsory_tutorial: true
  database:
    host: localhost
    port: 3306
    username: root
    password: password
    name: TeachingTutorials

#Progress Map
#Enable if you have a MapHub progress map
ProgressMap:
  enabled: false
  MapHubAPIKey: insert_api_key_here
  ProgressMapID: insert_map_id_here
  #A web link to the progress map
  Link: insert_link_to_map_here

#Homes
homes:
  enabled: true

#Chat Settings
chat:
  #Global allows for cross-server implementation of chat.
  #Requires the proxy-plugin which is built for Velocity.
  global_chat:
    enabled: true
    socket:
      IP: localhost
      port: 30589

    #Custom tab menu
    tab:
      enabled: true
  #Whether to announce role promotions in chat.
  announce_promotions: true

  #Tips in chat
  #Whether to enable tips in chat and at what frequency they should display.
  #Adding messages can be done in files in the 'tips' folder. One file for each builder role you want to display it to.
  #Frequency is in minutes.
  tips:
    enabled: true
    frequency: 5

#Tpll config.
#The min and max y are for searching altitude for teleport, set it to the same value as the world height.
tpll:
  enabled: true
  requires_permission: false
  min_y: -128
  max_y: 1360

#Enable regions and cross-server teleport.
#Regions must be enabled for cross-server teleport to function.
#Earth world must be specified on all servers as it is used to determine cross-server tpll to the earth server.
#To make sure the player is teleported to the correct world if multiple exist.
regions_enabled: true
global_teleport: true
earth_world: earth

#Should /ll be enabled.
ll_enabled: true

#Time before player is set to AFK (minutes).
afk: 5

#Radius to search in the nearby locations tab of the exploration menu, distance in kilometres.
navigation_radius: 200

#When staff approval is needed for Jr.Builder region requests.
#These values are only relevant if regions are enabled.
#Always means that staff approval is always required.
#Radius is the square radius around the region that is checked when determining whether staff approval is necessary.
#If a region in this radius is owned by someone else staff approval will be needed.
#If you want to disable this entirely, set the radius to 0.
staff_request:
  always: false
  radius: 5

#Number of days a region owner can be inactive before they are demoted to member.
#If the region has no other members then the owner does not get demoted by the region becomes 'inactive'.
region_inactivity: 30

#Discord link
discord: 'https://discord.gg/5m56EgEVW6'

#Progression
progression:
  enabled: false
  announce_level-ups:
    overall: false
    seasonal: true