#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Server configuration
#Server types: PLOT, EARTH, LOBBY, TUTORIAL
enabled: false
server_name: server_name
server_type: EARTH

#Chat Socket
socket:
  IP:
  port:

#Network messages
#%player% is a placeholder for the player name.
chat:
  join: '&e%player% has joined UKnet'
  leave: '&e%player% has left UKnet'

#Tpll config.
tpll:
  enabled: true
  requires_permission: false

#Enable regions and cross-server teleport.
#Regions must be enabled for cross-server teleport to function.
#Earth world must be specified on all servers as it is used to determine cross-server tpll to the earth server.
#To make sure the player is teleported to the correct world if multiple exist.
regions_enabled: true
global_teleport: true
earth_world: earth

#Number of days a region owner can be inactive before they are demoted to member.
#If the region has no other members then the owner does not get demoted by the region becomes 'inactive'.
region_inactivity: 30

#Movement limits.
max_y: 512
min_y: -128

#Old database details
#These are only necessary for UKnet1.0 to UKnet2.0 conversions.
database_uknet: minecraft_uknet