#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Server configuration
#Server types: PLOT, EARTH, LOBBY, TUTORIAL
enabled: false
server_name: server_name
server_type: EARTH

#Chat Socket
socket:
  IP:
  port:

#Network messages
#%player% is a placeholder for the player name.
chat:
  join: '&e%player% has joined UKnet'
  leave: '&e%player% has left UKnet'

#Tpll config.
tpll:
  enabled: true
  requires_permission: false

#Enable regions and cross-server teleport.
#Regions must be enabled for cross-server teleport to function.
#Earth world must be specified on all servers as it is used to determine cross-server tpll to the earth server.
#To make sure the player is teleported to the correct world if multiple exist.
regions_enabled: true
global_teleport: true
earth_world: earth

#Time before player is set to AFK (minutes).
afk: 5

#Radius to search in the nearby locations tab of the exploration menu, distance in kilometres.
navigation_radius: 200

#When staff approval is needed for Jr.Builder region requests.
#These values are only relevant if regions are enabled.
#Always means that staff approval is always required.
#Radius is the square radius around the region that is checked when determining whether staff approval is necessary.
#If a region in this radius is owned by someone else staff approval will be needed.
#If you want to disable this entirely, set the radius to 0.
staff_request:
  always: false
  radius: 5

#Number of days a region owner can be inactive before they are demoted to member.
#If the region has no other members then the owner does not get demoted by the region becomes 'inactive'.
region_inactivity: 30

#Movement limits.
max_y: 512
min_y: -128

#Old database details
#These are only necessary for UKnet1.0 to UKnet2.0 conversions.
database_uknet: minecraft_uknet

#Version warnings
version:
  earth: '&cThe Earth world is currently still using Minecraft 1.12.2 due to mod requirements, it is highly recommended to connect using this version with the BTE modpack. You can install the modpack by running the command &4/modpack&c.'
  plot: '&cThe plotsystem is running on Minecraft 1.18.2. Connecting with older versions will limit your access to available blocks and any blocks added in newer versions will not display correctly.'

#Modpack links
modpack:
  windows: 'https://s3.buildtheearth.net/public/installer/latest/BTEInstaller-windows.zip'
  mac: 'https://s3.buildtheearth.net/public/installer/latest/BTEInstaller-mac.dmg'
  linux: 'https://s3.buildtheearth.net/public/installer/latest/BTEInstaller-linux.AppImage'
  universal: 'https://s3.buildtheearth.net/public/installer/latest/BTEInstaller-universal.jar'

#Discord link
discord: 'https://discord.gg/5m56EgEVW6'