#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Server configuration
#Server types: PLOT, EARTH, LOBBY, TUTORIAL
enabled: false
server_name: server_name
server_type: earth

#Chat Socket
socket:
  IP:
  port:

#Network messages
#%player% is a placeholder for the player name.
chat:
  join: '&e%player% has joined UKnet'
  leave: '&e%player% has left UKnet'

#Tpll config.
tpll:
  enabled: true
  requires_permission: false

#Enable cross-server teleporting using region plugin.
global_teleport: true
earth_server: false
earth_world: earth

#Movement limits.
max_y: 512
min_y: -128

#Old database details
#These are only necessary for UKnet1.0 to UKnet2.0 conversions.
database_uknet: minecraft_uknet