#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  navigation: uknet_navigation
  region: uknet_regions

#Server configuration
enabled: false
server_name: server_name

#Chat Socket
socket:
  IP:
  port:

#Network messages
#%player% is a placeholder for the player name.
chat:
  join: '&e%player% has joined UKnet'
  leave: '&e%player% has left UKnet'

#Tpll config.
tpll:
  enabled: true
  requires_permission: false

#Enable cross-server using region plugin.
global_teleport: true

#Old database details
#These are only necessary for UKnet1.0 to UKnet2.0 conversions.
database_uknet: minecraft_uknet