# Config version, do not update this manually as it could break the config.
version: 1.1.0

#MySQL is mandatory for this plugin.
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  region: uknet_regions

#Server configuration
#Server types: PLOT, EARTH, LOBBY, TUTORIAL
enabled: false
server_name: server_name
server_type: EARTH

#Lobby info, only necessary if server type is LOBBY.
spawn:
  world: Lobby
  x: 1000.5
  y: 69.0
  z: -129.5
  yaw: -90
  pitch: 0

#Chat Socket
socket:
  IP:
  port:

#Network messages
#%player% is a placeholder for the player name.
chat:
  join: '&e%player% has joined UKnet'
  firstjoin: '&eWelcome to UKnet, %player%'
  leave: '&e%player% has left UKnet'

#Tpll config.
#The min and max y are for searching altitude for teleport, set it to the same value as the world height.
tpll:
  enabled: true
  requires_permission: false
  min_y: -128
  max_y: 1360

#Enable regions and cross-server teleport.
#Regions must be enabled for cross-server teleport to function.
#Earth world must be specified on all servers as it is used to determine cross-server tpll to the earth server.
#To make sure the player is teleported to the correct world if multiple exist.
regions_enabled: true
global_teleport: true
earth_world: earth

#Time before player is set to AFK (minutes).
afk: 5

#Radius to search in the nearby locations tab of the exploration menu, distance in kilometres.
navigation_radius: 200

#When staff approval is needed for Jr.Builder region requests.
#These values are only relevant if regions are enabled.
#Always means that staff approval is always required.
#Radius is the square radius around the region that is checked when determining whether staff approval is necessary.
#If a region in this radius is owned by someone else staff approval will be needed.
#If you want to disable this entirely, set the radius to 0.
staff_request:
  always: false
  radius: 5

#Number of days a region owner can be inactive before they are demoted to member.
#If the region has no other members then the owner does not get demoted by the region becomes 'inactive'.
region_inactivity: 30

#Old database details
#These are only necessary for UKnet1.0 to UKnet2.0 conversions.
database_uknet: minecraft_uknet

#Discord link
discord: 'https://discord.gg/5m56EgEVW6'

#Discord role ids
role_id:
  architect:
  builder:
  jrbuilder:
  apprentice:
  applicant: