name: Network
version: '${project.version}'
main: net.bteuk.network.Network
api-version: '1.21.1'

dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    DecentHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    TeachingTutorials:
      load: BEFORE
      required: false
      join-classpath: false