name: Network
version: '${project.version}'
main: net.bteuk.network.Network
api-version: '1.21.1'

WorldGuard:
  load: AFTER
  required: true
  join-classpath: true
ProtocolLib:
  load: AFTER
  required: true
  join-classpath: true
LuckPerms:
  load: AFTER
  required: true
  join-classpath: true
DecentHolograms:
  load: AFTER
  required: false
  join-classpath: true