name: Network
version: '${project.version}'
main: net.bteuk.network.Network
api-version: 1.21.1
depend: [ WorldGuard, ProtocolLib, LuckPerms ]

softdepend:
  - DecentHolograms
  - TerraPlusMinus

commands:
  phead:
    usage: /<command>
    description: Get the player head of someone who has connected to the server.
  ban:
    usage: /<command>
    description: Bans a player for a specific duration and reason.
  mute:
    usage: /<command>
    description: Mutes a player for a specific duration and reason.
  kick:
    usage: /<command>
    description: Kick a player for the server.
  unban:
    usage: /<command>
    description: Unban a previously banned player.
  unmute:
    usage: /<command>
    description: Unmute a previously muted player.
  hdb:
    usage: /<command>
    description: Added so it can be routed to /skulls
  progressmap:
    usage: /<command>
    description: Sends a link of the progress map
    aliases:
      - progress
  tips:
    aliases: [ toggletips, tipstoggle ]
    usage: /<command>
    description: Toggles tips in chat.
  ptime:
    usage: /<command>
    description: Sets the time of day for the player
  season:
    usage: /<command>
    description: Command for creating, starting and ending seasons.
    aliases: [ seasons ]
  exp:
    usage: /<command>
    description: Test command for adding exp.
  buildingcompanion:
    usage: /<command>
    description: Toggle the building companion.
    aliases: [ bc, companion ]
  map:
    usage: /<command>
    description: Map command.
  pmute:
    usage: /<command>
    description: Mute a player
  punmute:
    usage: /<command>
    description: Unmute a player
  msg:
    aliases: [ w, tell ]
    usage: /<command>
    description: Sends a direct message to a player.
  promote:
    usage: /<command>
    description: Add a role to a player.
  demote:
    usage: /<command>
    description: Remove a role from a player.
  focus:
    aliases: [focusmode, fm]
    usage: /<command>
    description: Toggle focus mode, hides chat and players.
  me:
    usage: /<command>
    description: Disabled
  bteuk:
    usage: /<command>
    description: Test