name: Network
version: '${project.version}'
main: me.bteuk.network.Network
api-version: 1.18
depend: [ PlaceholderAPI, WorldGuard]

commands:
  plot:
    usage: /<command>
    description: Allows players to manipulate plots without using the gui.
  tpll:
    usage: /<command>
    description: Teleport to coordinates.
  navigator:
    aliases: [nav,gui,menu]
    usage: /<command>
    description: Opens the main gui, will always return to the previous menu if possible.
  staff:
    usage: /<command>
    description: Opens the Staff Menu.
  claim:
    usage: /<command>
    description: Routes directly to the build menu of the gui, mainly for the purpose of player habits as this was the command previously.
