name: Network
version: '${project.version}'
main: me.bteuk.network.Network
api-version: 1.18
depend: [ PlaceholderAPI ]

commands:
  plot:
    usage: /<command>
    description: Allows players to manipulate plots without using the gui.
  tpll:
    usage: /<command>
    description: Teleport to coordinates.
  navigator:
    aliases: [nav,gui,menu]
    usage: /<command>
    description: Opens the main gui targetting a relevant menu depending where the player is situated.
