name: Network
version: '${project.version}'
main: me.bteuk.network.Network
api-version: 1.18
depend: [ PlaceholderAPI, WorldGuard]

commands:
  plot:
    usage: /<command>
    description: Allows players to manipulate plots without using the gui.
  tpll:
    usage: /<command>
    description: Teleport to coordinates.
  ll:
    aliases: [location]
    usage: /<command>
    description: Returns the coordinates where the player is standing with a link to google maps.
  navigator:
    aliases: [nav,gui,menu,claim]
    usage: /<command>
    description: Opens the main gui, will always return to the previous menu if possible.
  staff:
    usage: /<command>
    description: Opens the Staff Menu.
  region:
    aliases: [region]
    usage: /<command>
    description: Allows players to manipulate regions without using the gui.
  teleport:
    aliasses: [tp]
    usage: /<command>
    description: Teleport to any online player.
  back:
    usage: /<command>
    description: Teleports the player to the previous teleported location.
  modpack:
    usage: /<command>
    description: Sends links to the BTE modpack download, can be configured in the plugin config.
  discord:
    usage: /<command>
    description: Sends a link to our discord server.
  nightvision:
    aliases: [nv]
    usage: /<command>
    description: Toggle nightvision.
  speed:
    usage: /<command>
    description: Sets the players speed, value up to 10.
  help:
    usage: /<command>
    description: Help menu for information on commands and server features.
  warp:
    usage: /<command>
    description: Warp to locations in the exploration menu.