name: Network
version: '${project.version}'
main: net.bteuk.network.Network
api-version: 1.20
depend: [ WorldGuard, ProtocolLib, LuckPerms ]

softdepend:
  - DecentHolograms

commands:
  plot:
    aliases: [ plots ]
    usage: /<command>
    description: Allows players to manipulate plots without using the gui.
  tpll:
    usage: /<command>
    description: Teleport to coordinates.
  ll:
    aliases: [ location, where ]
    usage: /<command>
    description: Returns the coordinates where the player is standing with a link to google maps.
  navigator:
    aliases: [ nav, gui, menu, claim ]
    usage: /<command>
    description: Opens the main gui, will always return to the previous menu if possible.
  staff:
    aliases: [ st ]
    usage: /<command>
    description: Opens the Staff Menu.
  region:
    usage: /<command>
    description: Allows players to manipulate regions without using the gui.
  teleport:
    aliases: [ tp ]
    usage: /<command>
    description: Teleport to any online player.
  back:
    usage: /<command>
    description: Teleports the player to the previous teleported location.
  teleporttoggle:
    aliases: [ tptoggle, toggleteleport, toggletp ]
    usage: /<command>
    description: Enables/Disables the ability for other players to teleport to you.
  discord:
    usage: /<command>
    description: Sends a link to our discord server.
  nightvision:
    aliases: [ nv ]
    usage: /<command>
    description: Toggle nightvision.
  speed:
    usage: /<command>
    description: Sets the players speed, value up to 10.
  help:
    usage: /<command>
    description: Help menu for information on commands and server features.
  warp:
    usage: /<command>
    description: Warp to locations in the exploration menu.
  warps:
    usage: /<command>
    description: List all warps on the server, 16 per page.
  navigation:
    usage: /<command>
    description: Adds commands to do with navigation.
  afk:
    usage: /<command>
    description: Toggles afk status.
  lobby:
    usage: /<command>
    description: Command for all lobby management.
  sethome:
    usage: /<command>
    description: Set a home to your current location.
  home:
    usage: /<command>
    description: Teleport to your home.
  delhome:
    usage: /<command>
    description: Delete a home.
  rules:
    usage: /<command>
    description: Get rules book.
  clear:
    usage: /<command>
    description: Clears your inventory.
  debugstick:
    usage: /<command>
    description: Get the debug stick.
  light:
    usage: /<command>
    description: Get a light block.
  barrier:
    usage: /<command>
    description: Get a barrier block.
  spawn:
    usage: /<command>
    description: Teleport to spawnpoint in lobby.
  zone:
    usage: /<command>
    description: Zone command.
  server:
    usage: /<command>
    description: Switch server by command.
  gamemode:
    aliases: [ gm ]
    usage: /<command>
    description: Switch gamemode.
  phead:
    usage: /<command>
    description: Get the player head of someone who has connected to the server.
  homes:
    usage: /<command>
    description: Like warps, but for homes, shows all homes the player has set.
  ban:
    usage: /<command>
    description: Bans a player for a specific duration and reason.
  mute:
    usage: /<command>
    description: Mutes a player for a specific duration and reason.
  kick:
    usage: /<command>
    description: Kick a player for the server.
  unban:
    usage: /<command>
    description: Unban a previously banned player.
  unmute:
    usage: /<command>
    description: Unmute a previously muted player.
  hdb:
    usage: /<command>
    description: Added so it can be routed to /skulls
  progressmap:
    usage: /<command>
    description: Sends a link of the progress map
    aliases:
      - progress
  tips:
    aliases: [ toggletips, tipstoggle ]
    usage: /<command>
    description: Toggles tips in chat.
  ptime:
    usage: /<command>
    description: Sets the time of day for the player
  season:
    usage: /<command>
    description: Command for creating, starting and ending seasons.
    aliases: [ seasons ]
  exp:
    usage: /<command>
    description: Test command for adding exp.
  buildingcompanion:
    usage: /<command>
    description: Toggle the building companion.
    aliases: [ bc, companion ]
  map:
    usage: /<command>
    description: Map command.
  pmute:
    usage: /<command>
    description: Mute a player
  punmute:
    usage: /<command>
    description: Unmute a player
  msg:
    aliases: [ w, tell ]
    usage: /<command>
    description: Sends a direct message to a player.
  promote:
    usage: /<command>
    description: Add a role to a player.
  demote:
    usage: /<command>
    description: Remove a role from a player.
  focus:
    aliases: [focusmode, fm]
    usage: /<command>
    description: Toggle focus mode, hides chat and players.